import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import type { EmailMessage, MailAccount } from "../api/types";
import { EmailComposer } from "../components/EmailComposer";

const emptyLead = "00000000-0000-0000-0000-000000000000";

function normalizeEmailHtml(value: string): string {
  const trimmed = value.trim();
  if (!/&lt;|&gt;|&amp;lt;|&amp;gt;/i.test(trimmed)) return trimmed;
  const holder = document.createElement("textarea");
  holder.innerHTML = trimmed;
  return holder.value;
}

export function InboxPage() {
  const [messages, setMessages] = useState<EmailMessage[]>([]); const [accounts, setAccounts] = useState<MailAccount[]>([]);
  const [folder, setFolder] = useState<"Incoming"|"Outgoing"|"All">("Incoming"); const [selected, setSelected] = useState<EmailMessage | null>(null); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [compose, setCompose] = useState(false); const [reply, setReply] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string|null>(null); const [channel, setChannel] = useState<"all"|"email">("all");
  const load = () => Promise.all([api.listEmails(), api.listMailAccounts()]).then(([m,a]) => { setMessages(m); setAccounts(a); if (selected && !m.some(x => x.id === selected.id)) setSelected(null); }).catch((e:Error)=>setError(e.message));
  useEffect(()=>{void load();},[]);
  const visible = useMemo(()=>messages.filter((m)=>(folder==="All"||m.direction===folder)&&(channel==="all"||channel==="email")),[messages,folder,channel]);
  const syncAll = async () => { setBusy(true); setError(null); try { for (const account of accounts.filter((a)=>a.isActive)) await api.syncMailAccount(account.id); await load(); } catch(e){setError((e as Error).message);} finally{setBusy(false);} };
  const toggle = (id: string) => setSelectedIds(ids => ids.includes(id) ? ids.filter(x => x !== id) : [...ids, id]);
  const deleteSelected = async () => { if (!selectedIds.length || !confirm(`¿Eliminar ${selectedIds.length} correo(s) solo de Leal Control?`)) return; setBusy(true); try { for (const id of selectedIds) await api.deleteEmail(id); setSelectedIds([]); await load(); } catch(e){setError((e as Error).message);} finally{setBusy(false);} };
  const createLead = async () => { if (!selected) return; setBusy(true); setError(null); try { await api.captureLead({ companyName: selected.fromAddress.split("@")[1] || "Nuevo contacto", contactName: selected.fromAddress, email: selected.fromAddress, source: "Email", description: `Correo recibido: ${selected.subject}`, notes: selected.bodyPreview }); await load(); } catch(e){setError((e as Error).message);} finally{setBusy(false);} };
  return <div className="inbox-page page-wide"><div className="page-head"><div><span className="eyebrow">COMUNICACIONES</span><h1>Bandeja omnicanal</h1><p className="muted">Conversaciones comerciales vinculadas con CRM y comprobantes.</p></div><div className="toolbar"><button className="btn btn-outline" onClick={()=>void syncAll()} disabled={busy}>Recibir correo</button><button className="btn" onClick={()=>setCompose(true)}>+ Nuevo email</button></div></div>{error&&<div className="alert">{error}</div>}
    <div className="channel-filter card"><button className={channel==="all"?"selected":""} onClick={()=>setChannel("all")}><span>✦</span><b>Todos</b><small>{messages.length}</small></button><button className={channel==="email"?"selected":""} onClick={()=>setChannel("email")}><span>✉</span><b>Email</b><small>{messages.length}</small></button><button className="channel-disabled" disabled><span>◉</span><b>WhatsApp</b><small>Próximo</small></button><button className="channel-disabled" disabled><span>◎</span><b>Instagram</b><small>Próximo</small></button><button className="channel-disabled" disabled><span>f</span><b>Facebook</b><small>Próximo</small></button></div>
    <div className="inbox-shell card"><aside className="inbox-folders"><button className={folder==="Incoming"?"active":""} onClick={()=>setFolder("Incoming")}><span>Entrada</span><strong>{messages.filter((m)=>m.direction==="Incoming").length}</strong></button><button className={folder==="Outgoing"?"active":""} onClick={()=>setFolder("Outgoing")}><span>Enviados</span><strong>{messages.filter((m)=>m.direction==="Outgoing").length}</strong></button><button className={folder==="All"?"active":""} onClick={()=>setFolder("All")}><span>Todos</span><strong>{messages.length}</strong></button><Link to="/configuracion/correo">Configurar cuentas</Link></aside>
      <section className="message-list"><div className="message-list-toolbar"><label><input type="checkbox" checked={visible.length > 0 && visible.every(m => selectedIds.includes(m.id))} onChange={e => setSelectedIds(e.target.checked ? visible.map(m=>m.id) : [])} /> Seleccionar</label>{selectedIds.length > 0 && <button className="btn btn-danger compact" onClick={()=>void deleteSelected()} disabled={busy}>Eliminar seleccionados</button>}</div>{visible.map((message)=><article key={message.id} className={`message-item ${selected?.id===message.id?"active":""}`}><input type="checkbox" checked={selectedIds.includes(message.id)} onChange={()=>toggle(message.id)} /><button onClick={()=>setSelected(message)}><span className={`direction-dot ${message.direction.toLowerCase()}`}/><div><strong>{message.direction==="Incoming"?message.fromAddress:message.toAddresses}</strong><b>{message.subject || "(sin asunto)"}</b><small>{message.bodyPreview.slice(0,130)}</small></div><time>{new Date(message.occurredAtUtc).toLocaleDateString("es-AR")}</time></button></article>)}{visible.length===0&&<div className="empty-state">No hay mensajes en esta bandeja.</div>}</section>
      <section className="message-reader">{selected?<><div className="reader-actions"><button className="btn btn-outline compact" onClick={()=>setReply(true)}>↩ Responder</button>{selected.direction==="Incoming" && !selected.relatedEntityId && <button className="btn compact" onClick={createLead}>＋ Abrir lead</button>}<button className="btn btn-danger compact" onClick={()=>{setSelectedIds([selected.id]);void deleteSelected();}}>Eliminar localmente</button></div><span className="eyebrow">{selected.direction==="Incoming"?"RECIBIDO":"ENVIADO"}</span><h2>{selected.subject || "(sin asunto)"}</h2><div className="message-addresses"><strong>De:</strong> {selected.fromAddress}<br/><strong>Para:</strong> {selected.toAddresses}</div>{selected.bodyHtml ? <iframe className="message-html" title="Contenido del correo" sandbox="allow-popups allow-popups-to-escape-sandbox" srcDoc={normalizeEmailHtml(selected.bodyHtml)} /> : <div className="message-body">{selected.bodyPreview}</div>}{selected.relatedEntityType&&<div className="entity-link">Vinculado con {selected.relatedEntityType}</div>}{reply&&<EmailComposer context={{entityType:selected.relatedEntityType || "Email",entityId:selected.relatedEntityId || emptyLead,to:selected.fromAddress,subject:selected.subject.startsWith("Re:")?selected.subject:`Re: ${selected.subject}`,body:`\n\n--- Mensaje original ---\n${selected.bodyPreview}`,inReplyTo:selected.internetMessageId}} onClose={()=>setReply(false)} onSent={load}/>}</>:<div className="empty-state">Seleccioná un mensaje para leerlo.</div>}</section>
    </div>{compose&&<EmailComposer context={{entityType:"General",entityId:emptyLead,subject:"",body:""}} onClose={()=>setCompose(false)} onSent={load}/>}</div>;
}
