import { useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { api } from "../api/client";
import type { ProductionRoute, ProductionWorkCenter, Product } from "../api/types";

type OperationDraft = { workCenterId: string; sequence: number; code: string; name: string; setupMinutes: number; runMinutesPerUnit: number; isQualityCheckpoint: boolean };

export function ProductionSetupPage() {
  const kind = useLocation().pathname.split("/").pop();
  const [centers, setCenters] = useState<ProductionWorkCenter[]>([]); const [routes, setRoutes] = useState<ProductionRoute[]>([]); const [products, setProducts] = useState<Product[]>([]);
  const [code, setCode] = useState(""); const [centerName, setCenterName] = useState(""); const [capacity, setCapacity] = useState(8); const [message, setMessage] = useState<string | null>(null);
  const [routeId, setRouteId] = useState(""); const [productId, setProductId] = useState(""); const [version, setVersion] = useState("1.0"); const [routeName, setRouteName] = useState(""); const [operations, setOperations] = useState<OperationDraft[]>([]);
  useEffect(() => { if (kind === "centros") api.listProductionWorkCenters().then(setCenters).catch(() => setCenters([])); if (kind === "rutas") { api.listProductionWorkCenters().then(setCenters).catch(() => setCenters([])); api.listProducts("", "Product", "", true).then(setProducts).catch(() => setProducts([])); api.listProductionRoutes().then(setRoutes).catch(() => setRoutes([])); } }, [kind]);
  const saveCenter = async () => { try { await api.createProductionWorkCenter({ code, name: centerName, description: null, capacityHoursPerDay: capacity }); setMessage("Centro guardado correctamente."); setCode(""); setCenterName(""); setCenters(await api.listProductionWorkCenters()); } catch (e) { setMessage(e instanceof Error ? e.message : "No se pudo guardar el centro."); } };
  const addOperation = () => setOperations(xs => [...xs, { workCenterId: centers[0]?.id ?? "", sequence: xs.length + 1, code: `OP-${xs.length + 1}`, name: "Nueva operación", setupMinutes: 0, runMinutesPerUnit: 0, isQualityCheckpoint: false }]);
  const editRoute = (route: ProductionRoute) => { setRouteId(route.id); setProductId(route.productId); setVersion(route.version); setRouteName(route.name); setOperations(route.operations.map(x => ({ workCenterId: x.workCenterId, sequence: x.sequence, code: x.code, name: x.name, setupMinutes: x.setupMinutes, runMinutesPerUnit: x.runMinutesPerUnit, isQualityCheckpoint: x.isQualityCheckpoint }))); };
  const saveRoute = async () => { try { const body = { productId, version, name: routeName, isActive: true, operations }; if (routeId) await api.updateProductionRoute(routeId, body); else await api.createProductionRoute(body); setMessage("Ruta guardada correctamente."); setRouteId(""); setOperations([]); setRoutes(await api.listProductionRoutes()); } catch (e) { setMessage(e instanceof Error ? e.message : "No se pudo guardar la ruta."); } };
  if (kind === "centros") return <div className="production-page page-wide"><div className="page-head"><div><span className="eyebrow">PRODUCCIÓN · CONFIGURACIÓN</span><h1>Centros de trabajo</h1><p className="muted">Máquinas, sectores o puestos donde se realizan operaciones.</p></div><Link className="btn btn-outline" to="/produccion">← Maestro</Link></div><div className="split"><section className="card pad"><h2>Nuevo centro</h2><label>Código<input value={code} onChange={e => setCode(e.target.value)} placeholder="CORTE-01" /></label><label>Nombre<input value={centerName} onChange={e => setCenterName(e.target.value)} placeholder="Sector de corte" /></label><label>Capacidad diaria<input type="number" min=".1" value={capacity} onChange={e => setCapacity(Number(e.target.value))} /></label>{message && <div className="success-banner">{message}</div>}<button className="btn" disabled={!code.trim() || !centerName.trim() || capacity <= 0} onClick={() => void saveCenter()}>Guardar centro</button></section><section className="card pad"><h2>Centros registrados</h2>{centers.map(x => <div className="production-setup-row" key={x.id}><strong>{x.code} · {x.name}</strong><span className="badge ok">{x.capacityHoursPerDay} h/día</span></div>)}{!centers.length && <p className="muted">Todavía no hay centros.</p>}</section></div></div>;
  if (kind === "rutas") return <div className="production-page page-wide"><div className="page-head"><div><span className="eyebrow">PRODUCCIÓN · CONFIGURACIÓN</span><h1>Rutas y operaciones</h1><p className="muted">Definí el orden de fabricación y sus tiempos.</p></div><Link className="btn btn-outline" to="/produccion">← Maestro</Link></div><div className="split"><section className="card pad"><h2>{routeId ? "Editar ruta" : "Nueva ruta"}</h2><label>Producto terminado<select value={productId} onChange={e => setProductId(e.target.value)}><option value="">Seleccionar producto</option>{products.map(x => <option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><div className="grid-2"><label>Versión<input value={version} onChange={e => setVersion(e.target.value)} /></label><label>Nombre<input value={routeName} onChange={e => setRouteName(e.target.value)} placeholder="Ruta estándar" /></label></div>{operations.map((op, i) => <div className="production-operation-row" key={i}><input type="number" min="1" value={op.sequence} onChange={e => setOperations(xs => xs.map((x, j) => j === i ? { ...x, sequence: Number(e.target.value) } : x))} /><select value={op.workCenterId} onChange={e => setOperations(xs => xs.map((x, j) => j === i ? { ...x, workCenterId: e.target.value } : x))}>{centers.map(x => <option key={x.id} value={x.id}>{x.code}</option>)}</select><input value={op.name} onChange={e => setOperations(xs => xs.map((x, j) => j === i ? { ...x, name: e.target.value } : x))} /><input type="number" min="0" value={op.runMinutesPerUnit} onChange={e => setOperations(xs => xs.map((x, j) => j === i ? { ...x, runMinutesPerUnit: Number(e.target.value) } : x))} placeholder="min/unidad" /><button className="btn btn-danger compact" type="button" onClick={() => setOperations(xs => xs.filter((_, j) => j !== i))}>×</button></div>)}<div className="toolbar"><button className="btn btn-outline" type="button" onClick={addOperation}>+ Operación</button><button className="btn" disabled={!productId || !routeName.trim() || !operations.length} onClick={() => void saveRoute()}>{routeId ? "Actualizar ruta" : "Guardar ruta"}</button></div>{message && <div className="success-banner">{message}</div>}</section><section className="card pad"><h2>Rutas registradas</h2>{routes.map(x => <div className="production-setup-row" key={x.id}><div><strong>{x.version} · {x.name}</strong><span className="muted">{x.operations.length} operaciones</span></div><button className="btn btn-outline compact" onClick={() => editRoute(x)}>Editar</button></div>)}{!routes.length && <p className="muted">Todavía no hay rutas.</p>}</section></div></div>;
  return <div className="production-page page-wide"><div className="page-head"><div><span className="eyebrow">PRODUCCIÓN · CONFIGURACIÓN</span><h1>Variantes de fabricación</h1><p className="muted">Organizá modelos, talles, colores y configuraciones.</p></div><Link className="btn btn-outline" to="/produccion">← Maestro</Link></div><div className="card pad production-setup-empty"><span>⚒</span><h2>Variantes vinculadas a la BOM</h2><p className="muted">Las variantes se aplican desde las líneas de la estructura de materiales para evitar duplicar productos.</p></div></div>;
}
