import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import type { ProductionBom, ProductionOrder, Product } from "../api/types";
import { ExcelToolbar } from "../components/ExcelTools";

const statuses = ["Borrador", "Planificada", "Liberada", "En proceso", "Pausada", "Completada", "Cancelada"];
export function ProductionOrdersPage() {
  const [orders,setOrders]=useState<ProductionOrder[]>([]); const [products,setProducts]=useState<Product[]>([]); const [boms,setBoms]=useState<ProductionBom[]>([]); const [number,setNumber]=useState(""); const [productId,setProductId]=useState(""); const [bomId,setBomId]=useState(""); const [quantity,setQuantity]=useState(1); const [message,setMessage]=useState<string|null>(null);
  const refresh=()=>api.listProductionOrders().then(setOrders).catch(()=>setOrders([]));
  useEffect(()=>{ api.listProducts("","Product","",true).then(setProducts).catch(()=>setProducts([])); refresh(); },[]);
  useEffect(()=>{ if(productId) api.listProductionBoms(productId).then(setBoms).catch(()=>setBoms([])); else setBoms([]); setBomId(""); },[productId]);
  const create=async()=>{setMessage(null);try{await api.createProductionOrder({number,productId,bomId:bomId||null,plannedQuantity:quantity,unit:products.find(x=>x.id===productId)?.baseUnit||"UN",plannedStartUtc:null,plannedEndUtc:null,notes:null});setMessage("Orden creada correctamente.");setNumber("");setQuantity(1);refresh();}catch(e){setMessage(e instanceof Error?e.message:"No se pudo crear la orden.");}};
  const change=async(id:string,status:number)=>{try{await api.updateProductionOrderStatus(id,status);refresh();}catch(e){setMessage(e instanceof Error?e.message:"No se pudo cambiar el estado.");}};
  return <div className="production-page page-wide"><div className="page-head"><div><span className="eyebrow">PRODUCCIÓN · EJECUCIÓN</span><h1>Órdenes de producción</h1><p className="muted">Planificá y seguí cada fabricación desde un único lugar.</p></div><Link className="btn btn-outline" to="/produccion/flujo">Ver flujo</Link></div><div className="split"><section className="card pad"><h2>Nueva orden</h2><div className="grid-2"><label>Número<input value={number} onChange={e=>setNumber(e.target.value)} placeholder="OP-0001" /></label><label>Cantidad<input type="number" min="0.0001" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label></div><label>Producto terminado<select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Seleccionar producto</option>{products.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label><label>BOM (opcional)<select value={bomId} onChange={e=>setBomId(e.target.value)}><option value="">Sin seleccionar</option>{boms.map(b=><option key={b.id} value={b.id}>{b.version} · {b.name}</option>)}</select></label>{message&&<div className="success-banner">{message}</div>}<button className="btn" disabled={!number.trim()||!productId||quantity<=0} onClick={()=>void create()}>Crear orden</button></section><section className="card pad"><h2>Órdenes registradas</h2>{orders.map(order=><div className="production-order-row" key={order.id}><div><Link className="strong-link" to={`/produccion/ordenes/${order.id}`}>{order.number}</Link><span className="muted">{products.find(p=>p.id===order.productId)?.name||order.productId} · {order.plannedQuantity} {order.unit}</span></div><select value={order.status} onChange={e=>void change(order.id,Number(e.target.value))}>{statuses.map((s,i)=><option value={i} key={s}>{s}</option>)}</select></div>)}{!orders.length&&<p className="muted">Todavía no hay órdenes de producción.</p>}</section></div></div>;
}
