import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import type { PurchaseInvoice, PurchaseOrder, PurchaseReception, PurchaseRequest } from "../api/types";

const orderLabels: Record<string, string> = { Draft: "Borrador", Sent: "Enviada", PartiallyReceived: "Parcial", Received: "Recibida", Cancelled: "Cancelada" };

export function PurchasesDashboardPage() {
  const [requests, setRequests] = useState<PurchaseRequest[]>([]);
  const [orders, setOrders] = useState<PurchaseOrder[]>([]);
  const [receptions, setReceptions] = useState<PurchaseReception[]>([]);
  const [invoices, setInvoices] = useState<PurchaseInvoice[]>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([api.listPurchaseRequests(), api.listPurchaseOrders(), api.listPurchaseReceptions(), api.listPurchaseInvoices()]).then(([r, o, rec, i]) => { setRequests(r); setOrders(o); setReceptions(rec); setInvoices(i); }).catch(e => setError(e instanceof Error ? e.message : "No se pudo cargar el tablero.")); }, []);
  const pending = useMemo(() => orders.filter(o => o.status === "Draft" || o.status === "Sent" || o.status === "PartiallyReceived"), [orders]);
  const requestPending = requests.filter(r => r.status === "Pending").length;
  const invoicePending = invoices.filter(i => i.status !== "Paid" && i.status !== "Cancelled").length;
  return <div className="page-wide"><div className="page-head"><div><span className="eyebrow">ABASTECIMIENTO · CENTRO DE CONTROL</span><h1>Compras</h1><p className="muted">Todo el circuito de abastecimiento en una sola vista.</p></div><div className="toolbar"><Link className="btn btn-outline" to="/compras/solicitudes/nueva">+ Solicitud</Link><Link className="btn" to="/compras/ordenes/nueva">+ Orden de compra</Link></div></div>{error && <div className="alert">{error}</div>}<div className="kpi kpi-4"><div className="card"><span className="muted">Solicitudes por aprobar</span><strong>{requestPending}</strong></div><div className="card"><span className="muted">Órdenes abiertas</span><strong>{pending.length}</strong></div><div className="card"><span className="muted">Recepciones registradas</span><strong>{receptions.length}</strong></div><div className="card"><span className="muted">Facturas pendientes</span><strong>{invoicePending}</strong></div></div><div className="split"><section className="card pad"><div className="section-head"><div><h2>Próximas acciones</h2><p className="muted">Documentos que requieren atención.</p></div></div>{requests.filter(r => r.status === "Pending").slice(0, 5).map(r => <Link className="production-setup-row" key={r.id} to={`/compras/solicitudes/${r.id}`}><span><strong>{r.requestNumber}</strong> · {r.department}<small>{r.reason}</small></span><span className="badge warn">Aprobar</span></Link>)}{pending.slice(0, 5).map(o => <Link className="production-setup-row" key={o.id} to={`/compras/ordenes/${o.id}`}><span><strong>{o.orderNumber}</strong> · {o.supplierName}<small>{orderLabels[o.status]} · Entrega {o.expectedDeliveryDate ? new Date(o.expectedDeliveryDate).toLocaleDateString("es-AR") : "sin fecha"}</small></span><span className="badge">{orderLabels[o.status]}</span></Link>)}{!requests.some(r => r.status === "Pending") && !pending.length && <p className="muted">No hay acciones pendientes.</p>}</section><section className="card pad"><h2>Circuito de compra</h2><div className="help-flow"><div className="help-step"><span className="help-number">1</span><div><h3>Solicitar</h3><p>Necesidad interna y aprobación.</p></div></div><div className="help-step"><span className="help-number">2</span><div><h3>Comparar</h3><p>Cotizaciones y adjudicación.</p></div></div><div className="help-step"><span className="help-number">3</span><div><h3>Ordenar</h3><p>Pedido formal al proveedor.</p></div></div><div className="help-step"><span className="help-number">4</span><div><h3>Recibir</h3><p>Ingreso, calidad y diferencias.</p></div></div><div className="help-step"><span className="help-number">5</span><div><h3>Conciliar</h3><p>Orden, recepción y factura.</p></div></div></div></section></div></div>;
}
