import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import type { PurchaseInvoice, PurchaseOrder, PurchaseReception } from "../api/types";

export function PurchaseReportsPage() {
  const [orders, setOrders] = useState<PurchaseOrder[]>([]); const [receptions, setReceptions] = useState<PurchaseReception[]>([]); const [invoices, setInvoices] = useState<PurchaseInvoice[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([api.listPurchaseOrders(), api.listPurchaseReceptions(), api.listPurchaseInvoices()]).then(([o, r, i]) => { setOrders(o); setReceptions(r); setInvoices(i); }).catch(e => setError(e instanceof Error ? e.message : "No se pudieron cargar los reportes.")); }, []);
  const supplierStats = useMemo(() => { const map = new Map<string, { name: string; orders: number; amount: number; received: number }>(); orders.forEach(o => { const s = map.get(o.supplierId) || { name: o.supplierName, orders: 0, amount: 0, received: 0 }; s.orders++; s.amount += o.total; s.received += o.status === "Received" ? 1 : 0; map.set(o.supplierId, s); }); return [...map.values()].sort((a, b) => b.amount - a.amount); }, [orders]);
  const open = orders.filter(o => ["Draft", "Sent", "PartiallyReceived"].includes(o.status)); const overdue = open.filter(o => o.expectedDeliveryDate && new Date(o.expectedDeliveryDate) < new Date()).length; const total = orders.filter(o => o.status !== "Cancelled").reduce((n, o) => n + o.total, 0);
  return <div className="page-wide"><div className="page-head"><div><span className="eyebrow">COMPRAS · REPORTES</span><h1>Reportes y evaluación</h1><p className="muted">Visibilidad sobre gasto, cumplimiento y pendientes del abastecimiento.</p></div><Link className="btn btn-outline" to="/compras">← Centro de control</Link></div>{error && <div className="alert">{error}</div>}<div className="kpi kpi-4"><div className="card"><span className="muted">Gasto registrado</span><strong>{total.toLocaleString("es-AR", { minimumFractionDigits: 2 })}</strong></div><div className="card"><span className="muted">Órdenes abiertas</span><strong>{open.length}</strong></div><div className="card"><span className="muted">Entregas demoradas</span><strong>{overdue}</strong></div><div className="card"><span className="muted">Recepciones</span><strong>{receptions.length}</strong></div></div><div className="split"><section className="card pad"><h2>Evaluación por proveedor</h2><p className="muted">La puntuación inicial combina órdenes completadas y volumen comprado; luego podrá incorporar calidad, precio y puntualidad histórica.</p><div className="table-wrap"><table><thead><tr><th>Proveedor</th><th>Órdenes</th><th>Importe</th><th>Completadas</th><th>Cumplimiento</th></tr></thead><tbody>{supplierStats.map(s => <tr key={s.name}><td>{s.name}</td><td>{s.orders}</td><td>{s.amount.toLocaleString("es-AR", { minimumFractionDigits: 2 })}</td><td>{s.received}</td><td><span className={`badge ${s.received === s.orders ? "ok" : "warn"}`}>{s.orders ? Math.round((s.received / s.orders) * 100) : 0}%</span></td></tr>)}</tbody></table></div>{!supplierStats.length && <p className="muted">Aún no hay órdenes suficientes para evaluar proveedores.</p>}</section><section className="card pad"><h2>Alertas operativas</h2>{overdue > 0 && <div className="alert">Hay {overdue} orden(es) con fecha prevista vencida.</div>}<div className="production-setup-row"><span>Facturas registradas</span><strong>{invoices.length}</strong></div><div className="production-setup-row"><span>Órdenes canceladas</span><strong>{orders.filter(o => o.status === "Cancelled").length}</strong></div><div className="production-setup-row"><span>Recepciones parciales</span><strong>{orders.filter(o => o.status === "PartiallyReceived").length}</strong></div></section></div></div>;
}
