// <auto-generated />
using System;
using System.Collections.Generic;
using LealControl.Modules.Crm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LealControl.Modules.Crm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LealControl.Modules.Crm.Domain.Activities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextFollowUpOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CustomerId", "OccurredAtUtc");

                    b.ToTable("activities", "crm");
                });

            modelBuilder.Entity("LealControl.Modules.Crm.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTime?>("FceCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FceThreshold")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("IibbRegime")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLargeCompany")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSupplier")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("PaymentTermsDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxCondition")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LegalName");

                    b.ToTable("customers", "crm");
                });

            modelBuilder.Entity("LealControl.Modules.Crm.Domain.Customers.CustomerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("customer_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("customer_id");

                    b.ToTable("customer_contacts", "crm");
                });

            modelBuilder.Entity("LealControl.Modules.Crm.Domain.Customers.CustomerLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("customer_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("customer_id");

                    b.ToTable("customer_locations", "crm");
                });

            modelBuilder.Entity("LealControl.Modules.Crm.Domain.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("ConvertedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConvertedCustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("leads", "crm");
                });

            modelBuilder.Entity("LealControl.Modules.Crm.Domain.Opportunities.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("LostReason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("_tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Priority");

                    b.HasIndex("TenantId", "Stage");

                    b.ToTable("opportunities", "crm");
                });

            modelBuilder.Entity("LealControl.Modules.Crm.Domain.Customers.Customer", b =>
                {
                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers", "crm");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.PostalAddress", "FiscalAddress", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("fiscal_city");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("fiscal_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("fiscal_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("fiscal_street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers", "crm");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers", "crm");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.PhoneNumber", "WhatsApp", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("whatsapp");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers", "crm");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.PartyDocument", "Document", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("document_number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("document_type");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers", "crm");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsMany("LealControl.Modules.Crm.Domain.Customers.CustomerFiscalRate", "FiscalRates", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("ExclusionCertificateNumber")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<bool>("HasPerceptionExclusion")
                                .HasColumnType("boolean");

                            b1.Property<bool>("HasRetentionExclusion")
                                .HasColumnType("boolean");

                            b1.Property<string>("Jurisdiction")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateOnly?>("PerceptionExclusionExpiresOn")
                                .HasColumnType("date");

                            b1.Property<decimal>("PerceptionRate")
                                .HasPrecision(8, 4)
                                .HasColumnType("numeric(8,4)");

                            b1.Property<DateOnly?>("RetentionExclusionExpiresOn")
                                .HasColumnType("date");

                            b1.Property<decimal>("RetentionRate")
                                .HasPrecision(8, 4)
                                .HasColumnType("numeric(8,4)");

                            b1.Property<Guid>("customer_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("customer_id", "Jurisdiction")
                                .IsUnique();

                            b1.ToTable("customer_fiscal_rates", "crm");

                            b1.WithOwner()
                                .HasForeignKey("customer_id");
                        });

                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("FiscalAddress");

                    b.Navigation("FiscalRates");

                    b.Navigation("Phone");

                    b.Navigation("WhatsApp");
                });

            modelBuilder.Entity("LealControl.Modules.Crm.Domain.Customers.CustomerContact", b =>
                {
                    b.HasOne("LealControl.Modules.Crm.Domain.Customers.Customer", null)
                        .WithMany("Contacts")
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("CustomerContactId");

                            b1.ToTable("customer_contacts", "crm");

                            b1.WithOwner()
                                .HasForeignKey("CustomerContactId");
                        });

                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("CustomerContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone");

                            b1.HasKey("CustomerContactId");

                            b1.ToTable("customer_contacts", "crm");

                            b1.WithOwner()
                                .HasForeignKey("CustomerContactId");
                        });

                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.PhoneNumber", "WhatsApp", b1 =>
                        {
                            b1.Property<Guid>("CustomerContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("whatsapp");

                            b1.HasKey("CustomerContactId");

                            b1.ToTable("customer_contacts", "crm");

                            b1.WithOwner()
                                .HasForeignKey("CustomerContactId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Phone");

                    b.Navigation("WhatsApp");
                });

            modelBuilder.Entity("LealControl.Modules.Crm.Domain.Customers.CustomerLocation", b =>
                {
                    b.HasOne("LealControl.Modules.Crm.Domain.Customers.Customer", null)
                        .WithMany("Locations")
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.PostalAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerLocationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street");

                            b1.HasKey("CustomerLocationId");

                            b1.ToTable("customer_locations", "crm");

                            b1.WithOwner()
                                .HasForeignKey("CustomerLocationId");
                        });

                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("CustomerLocationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone");

                            b1.HasKey("CustomerLocationId");

                            b1.ToTable("customer_locations", "crm");

                            b1.WithOwner()
                                .HasForeignKey("CustomerLocationId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("LealControl.Modules.Crm.Domain.Leads.Lead", b =>
                {
                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "crm");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.OwnsOne("LealControl.Modules.Crm.Domain.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "crm");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("LealControl.Modules.Crm.Domain.Customers.Customer", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
